# Generated by Django 3.2.7 on 2022-01-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_is_staff_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_Active',
            new_name='is_active',
        ),
    ]
